clone_depth: 10

environment:
  matrix:
    - nodejs_version: 12
    - nodejs_version: 14
    - nodejs_version: 16

matrix:
  fast_finish: true

platform:
  - x64

version: "{build}"
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install

test_script:
  - npm test

cache:
  # global npm cache
  - '%APPDATA%\npm-cache'
